### ISSUE TITLE
Use finalized runtime pack format

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#10442]
SDK work:

- [x] Resolve runtime pack assets from `data/RuntimeList.xml` (proposed format is here: https://github.com/dotnet/core-setup/issues/6409)
- [x] Use platform manifest from runtime pack for conflict resolution for self-contained apps
  - Some discussion of this is here: https://github.com/dotnet/sdk/issues/2933

Runtime pack work:

- Microsoft.NETCore.App and Microsoft.WindowsDesktop.App
  - [x] Use final package names - https://github.com/dotnet/core-setup/issues/6508
    - [x] `Microsoft.NETCore.App.Runtime.<RID>`
    - [x] `Microsoft.WindowsDesktop.App.Runtime.<RID>`
    - [x] `Microsoft.NETCore.DotNetHostResolver.<RID>`
    - [x] `Microsoft.NETCore.DotNetHostPolicy.<RID>`
  - [x] Add runtime list - https://github.com/dotnet/core-setup/issues/6409)
  - [x] Add platform manifest - https://github.com/dotnet/core-setup/issues/6509
  - [x] Rename FrameworkList.xml to RuntimeList.xml in runtime packs - https://github.com/dotnet/core-setup/issues/6764
  - [x] Add Locale information about runtime pack resource DLLs to runtime pack manifest: https://github.com/dotnet/core-setup/issues/6768
- Microsoft.AspNeTCore.App
  - [x] Use final package name: `Microsoft.AspNetCore.App.Runtime.<RID>`
  - [x] Add runtime list - https://github.com/aspnet/AspNetCore/issues/10216
  - [x] Add platform manifest - https://github.com/aspnet/AspNetCore/issues/10474

**Comment by peterhuene** [comment]
Assigning this to @dsplaisted for tracking purposes.

**Comment by dsplaisted** [comment]
We will need a way to distinguish which files are native versus managed runtime implementations (because they are encoded differently in the deps.json).  There may also be files which are neither (such as .pdb or .map files).  As such, we will probably want a manifest in the runtime pack listing the files and how they are used.

**Comment by nguerrera** [comment]
We don't need to block on the file list as we have the nuget conventions intact for native vs. managed.

**Comment by nguerrera** [comment]
#10537
