### ISSUE TITLE
Improve CLI performance for RC2

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#2496]
Tracking issue for performance improvements for CLI

## Bugs
 - [x] https://github.com/dotnet/cli/issues/2476 The shared framework does not appear to be pre-compiled, or if it is, there are a very large number of methods that still get JIT compiled. 
 - [x] https://github.com/dotnet/cli/issues/2474 The CLI binaries themselves are not pre-compiled at all

## Enhancements
 - [x] https://github.com/dotnet/cli/issues/2483 Consider Performing C# Compilation in a Single Dotnet Process [CSC is the remaining candidate for moving in-proc. This is a high-risk change that we'd like to do in RTM.]
 - [x] ~~https://github.com/dotnet/cli/issues/2595 move telemetry to a fire-forget process (Moved to RTM)~~
 - [x] https://github.com/dotnet/cli/issues/2520 Static caching for project context
 - [x] https://github.com/dotnet/cli/issues/2521 Dotnet Build accepts multiple projects in single invocation
 - [x] https://github.com/dotnet/cli/issues/2522 add basic performance monitoring
 - [x] ~~???? IF ABOVE FAILS: CLI standalone + !R2R~~ standalone trades off one perf win [slightly faster] for a big perf loss [double the payload size]. 

## RTM Plan
RTM enhancements are being tracked in https://github.com/dotnet/cli/issues/2515

**Comment by piotrpMSFT** [comment]
@LakshanF @danquirk take note of the telemetry issue. As anticipated when we first talked about adding telemetry, there is a huge perf cost associated with sending the data. The proposal is to spin off a simple child process that will report on invoked command. Can you guys help with making this happen?

**Comment by muratg** [comment]
:eyes:

**Comment by DavidObando** [comment]
:eyes:

**Comment by Petermarcu** [comment]
All RC2 items are complete. Closing.
