### ISSUE TITLE
Improve error messages and/or help content in various commands

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/cli#3147]
This is an aggregate issue that tracks improving error messages in various commands for various cases. We should add to this issue whenever we find one. The current set below is based on feedback from users and testing.  
- [x] Add another sentence to `dotnet publish` to inform the user that publishing libraries is not a valid operation (see #3119)
- [x] Add valid configurations in help for `dotnet build`
- [ ] Add info that further options can be passed to the test runner (and point people to it) (see #3143)
- [x] Add a 1. (or fix the message entirely) for `dotnet run` when it runs against an invalid framework (see #2896)
- [x] Add a line that suggests running `dotnet restore` when there is no lock file (see #3051)
- [x] Change the error when running `dotnet test` and no `testRunner` is configured (see #3652)

/cc @brthor @livarcocc @Sridhar-MS @piotrpMSFT

**Comment by dasMulli** [comment]
There also still is #2896

**Comment by blackdwarf** [comment]
@dasMulli thanks, added in the list above.

**Comment by brthor** [comment]
> Add valid configurations in help for  dotnet build  

What does this mean?

**Comment by blackdwarf** [comment]
@brthor means that when you do `dotnet build --help` the entry for the `--configuration` argument should contain also the possible values (i.e. Debug, Release etc.)

**Comment by livarcocc** [comment]
The last missing issue has been moved to https://github.com/Microsoft/vstest/issues/794. Closing this one.
