### ISSUE TITLE
F# support in preview2

### ISSUE THREAD

**Issue by enricosada** [dotnet/cli#3631]
.NET Core SDK preview1 and F# works amazing ootb on all supported os  (win/osx/ubuntu/docker) :tada: thx @dotnet/cli team!

An example: [Suave working on preview1 in win/osx/ubuntu/docker](https://github.com/SuaveIO/Suave-CoreCLR-sample), suave is the web fw (library :P) used a lot by f# community

I'd like too track current issues for preview2 and fix some annoyances in preview1, so ootb should work like or better than preview1

Some issue are of this repo, other are referenced from dotnet/netcorecli-fsc but are needed for a good ootb experience

- [x] :no_entry_sign:  preview2 build doesnt work, ref https://github.com/dotnet/netcorecli-fsc/issues/12
- [ ] remove `compile-fsc` from `dotnet/cli` repo, and use package built from `dotnet/netcorecli-fsc`, pr #2638
- [x] enable portable pdb as default (like c#)?
- [x] f# project shouldnt require a nuget.config, for sure not with `<clear/>`
- [x] remove nuget.config from dotnet-new templates
- [x] simplify `compile-fsc` tools references, probabily some of import are useless
- [x] support serviceable attribute in compile-fsc
- [ ] same dotnet-new templates as c# ( lib #3627 , xunit TODO, web TODO = suave? )
- [x] check f# core and compiler package deps, no downgrade warning (ref #3506 )
- [ ] f# in dotnet homepage tutorial. in preview1 f# was ok, but there was no `--lang f#` to help new users in tutorial, or in homepage about "f# support is beta" at least

@blackdwarf @brthor  i am missing something new of preview2 from this list?

/cc @KevinRansom @dsyme @cartermp

**Comment by brthor** [comment]
The list looks good to me :+1: 

Will FSC core nuget packages get published to nuget, or how will you remove the need for nuget.config?

**Comment by cartermp** [comment]
> Will FSC core nuget packages get published to nuget, or how will you remove the need for nuget.config?

@KevinRansom Can we get the last stable build published to NuGet for Preview 2?  I believe we chatted about this at some point.

**Comment by enricosada** [comment]
@brthor  Yes, as i speak tuesday with @KevinRansom at visualfsharp standup and he is going to publish the version of compiler/fsharp.core package to nuget.org as prerelease.
`compile-fsc` too in nuget.org, but built from `dotnet/netcorecli-fsc` repo, so we can update easy

**Comment by brthor** [comment]
Very nice :+1:

**Comment by enricosada** [comment]
sry @cartermp  didint see you comment before posting.

@cartermp i'll check if publising a `-preview2` version of `compile-fsc` tool break existing `preview1` (the deps ref was `1.0.0.*` in `prevew1` :cry: ).

With preview1 use a nuget.config was really annoying, a lot, because use `<clear/>` and i fear of break `preview1` user if we publish in fsharp-daily feed, because it's used by default.
i think only dev should use fsharp-daily, now netcore support is stable

**Comment by enricosada** [comment]
@brthor preview2 expected release date is? i hope to at least before the code freeze:
- fix bug and publish a package fron netcorecli-fsc repo .
- fix dotnet new (adding lib template if possibile, is really useful as example)

**Comment by enricosada** [comment]
@brthor i fixed #3467 to address some important points, so f# should be ready for `preview2` release.\
we can fix compiler bug later these days (and publish the fixed package), but at least defaults for `dotnet new` are good. 
it's really important for OOTB experience, with `preview1` was nice

**Comment by blackdwarf** [comment]
@enricosada what is the status of this?

**Comment by enricosada** [comment]
i think can be closed, `preview2` works with f#, and fixed templates for `dotnet new --lang f#` are already committed.
There are [getting started docs](https://dotnet.github.io/docs/getting-started/index.html) and [wiki/faq](https://github.com/dotnet/netcorecli-fsc/wiki/FAQ)

Thx a lot @blackdwarf @brthor @piotrpMSFT for support!

cya soon, i'll check the msbuild support there too for fsproj :D
