### ISSUE TITLE
ProjectJson To CSProj Migration Tracking Issue

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#4096]
**Migration Blocking Issues**
- [x] https://github.com/Microsoft/msbuild/issues/970 Globbed Excludes do not work on OS X 
- [x] https://github.com/dotnet/sdk/issues/30 Short to Full TFM Mapping

**High Priority Items**
- [x] https://github.com/dotnet/cli/issues/4223 Migrate ProjectDependencies for each framework
- [x] https://github.com/dotnet/cli/issues/4222 Migrate PackageRef
- [x] https://github.com/dotnet/cli/issues/4215 Remove dependency on restore
- [x] https://github.com/dotnet/cli/issues/4201 BuildOptions under frameworks
- [x] https://github.com/dotnet/cli/issues/4167 Migrate sets of projects
- [x] https://github.com/dotnet/cli/issues/4164 Clean up Text Output
- [x] https://github.com/dotnet/cli/issues/4165 Create Migration Report
- [x] https://github.com/dotnet/cli/issues/4125 Support Script Environment variables
- [x] https://github.com/dotnet/cli/issues/4124 Migrate PackOptions
- [x] https://github.com/dotnet/cli/issues/4122 Migrate XProj P2P References
- [x] https://github.com/dotnet/cli/issues/4120 Don't output properties when they have the default value
- [x] https://github.com/dotnet/cli/issues/4097 Support Project.json Mappings
- [x] https://github.com/dotnet/cli/issues/4098 Recursively migrate P2P Dependencies
- [x] https://github.com/dotnet/cli/issues/4126 ~~**[blocked]** ExecShell for Script Extension inference~~
- [x] https://github.com/dotnet/cli/issues/4107 ~~**[blocked]**~~ Support excludes inside of a configuration
- [x] https://github.com/dotnet/cli/issues/4105 **[blocked]** Support projects with Multiple TFMs
- [x] https://github.com/dotnet/cli/issues/4106 **[blocked]** Support Script variable requiring a short TFM

**Low Priority Items**
- [ ] https://github.com/dotnet/cli/issues/4166 Handle Deprecated Projects Intelligently
- [ ] https://github.com/dotnet/cli/issues/4140 Mappings multiple source single destination copies last file in msbuild
- [x] https://github.com/dotnet/cli/issues/4099 ~~Non-CSharp projects, do they migrate?~~
- [x] https://github.com/dotnet/cli/issues/4081 Change dotnet new -t msbuild in help when it becomes the default
- [x] https://github.com/dotnet/cli/issues/4100 Redesign TransformApplicator based on PR Feedback
- [ ] https://github.com/dotnet/cli/issues/4101 **[blocked]** Remove msbuild.exe text file workaround when msbuild bug is fixed

**Done Items**
- [x] Enable dotnet-migrate command line
- [x] Migrate project.json BuildOptions
- [x] Migrate project.json P2P dependencies
- [x] Migrate project.json Configurations buildOptions
- [x] Migrate project.json Scripts
- [x] Migrate project.json Root Options
- [x] Migrate project.json Publish Options
- [x] Migrate project.json Runtime Options
- [x] MSbuild Item Merging algorithm
- [x] Add Sdk Reference to migrated project.json, remove runtimes
- [x] Use consistent error code pattern
- [x] BuildOptions Migration Unit Tests
- [x] P2P Migration Unit tests
- [x] Configurations Migration Unit Tests
- [x] Scripts Migration Unit Tests
- [x] Root Options Migration Unit Tests
- [x] Publish Options Migration Unit Tests
- [x] Runtime Options Migration Unit Tests
- [x] dotnet-migrate EndToEnd Output verification tests

**Non-migrateable Items Info**
- `scripts` with variables `compile:ResponseFile, compile:CompilerExitCode, compile:RuntimeOutputDir, compile:RuntimeIdentifier`

**Comment by livarcocc** [comment]
I am closing this. We have separate items for the two items that still need work.
