### ISSUE TITLE
CLI Migration Bug Bash

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#4747]
Attempt migrating a bunch of projects, identify bugs

**Comment by GuardRex** [comment]
Is this tracking issue for internal use, or did you want to hear about community `dotnet migration` problems, as well. I have a pair of small ones thus far (but they are being addressed in other issues).

**Comment by piotrpMSFT** [comment]
It was intended for internal tracking, but if the community wants to throw bugs our way we'd be obliged [as it allows us to spend time fixing bugs instead of hunting for them :D] :bug: :gun:

**Comment by GuardRex** [comment]
:+1: ... What we could do (e.g., @bartmax issues along with others) is just reference the open issues here and check them off as they're addressed. Either that, or I'll just filter CLI issues by the `migration` label. I'm particularly interested in what devs hit that are relevant for my upcoming doc updates.

- [ ] There's the Sdk package version restore we're talking about in https://github.com/dotnet/cli/issues/4751
- [ ] There's needed guidance for the loss of the `publish-iis` tooling in https://github.com/dotnet/cli/issues/4612#issuecomment-261213473 and https://github.com/aspnet/IISIntegration/pull/299#issuecomment-261149435. (I didn't see the dedicated issue until after I asked in the IISIntegration issue.)
- [ ] There's the Razor precomp package renaming: It would have been nice if the migration had swapped the package names :sparkles: auto-magically :sparkles: for me. https://github.com/aspnet/Razor/issues/864 ... and I'm still having just a bit of a prob, but @pranavkm is on the case on that issue.

**Comment by jvandertil** [comment]
Not sure if a bug caught me off guard:

1. Have 2 projects A, B with a reference B -> A
2. Convert A
3. Converting B fails with reference not found (project.json).

For example:
```
git clone https://github.com/jvandertil/ReflectionMagic.git
cd ReflectionMagic
git checkout dotnetcore

-- edit global.json to remove sdk reference --

dotnet migrate src\ReflectionMagic
dotnet migrate test\ReflectionMagicTests

> error:
Could not find file 'src\ReflectionMagic\project.json'.
Migration failed.
```

Reverting everything, editing the global.json again, and running a dotnet migrate from the root works without problems though.

**Comment by natemcmaster** [comment]
Ran into the same issue as @jvandertil when using VS 2017 RC migration. The `--skip-project-references` flag didn't seem to help. Repro: try converting [this code](https://github.com/aspnet/DotNetTools/tree/2a0e827f9b6b6161604fb94a687e155e404f005a) in VS 2017 RC.

**Comment by piotrpMSFT** [comment]
VS 2017 RC has a known issue where migration fails for multi-project solutions. It's due to conflicting backup strategies between the CLI and VS.

The original issue here is that the CLI has no way of knowing that a successfully migrated project might be depended on by projects it does not refer to... so it cleans up after itself. The solution here is to run migrate from the parent directory so `migrate` has the full context of all associated projects. Migrating in reverse order, having the dependent project migrate first, will also be successful since we know to migrate both. Finally, you can migrate projects with the --no-backup flag to disable cleanup of PJ's. In this case, the PJs will need to be cleaned up manually.

There is not an obvious 'right' answer here. The balance between cleaning up after ourselves and leaving enough context for arbitrary migration orders is pretty tough. We could think about looking in the `backup` directory for PJs but this is also non-deterministic since the solution root is inferred from the collection of projects being migrated in a given session so it can land at somewhat arbitrary locations in the directory hierarchy... sometimes far above the first common parent for any two projects. 

Do you folks have an idea for how we can improve the experience?

**Comment by natemcmaster** [comment]
> There is not an obvious 'right' answer here.

Yeah, it's a tricky situation. The only helpful suggestion I can make is that in some situations dotnet-migrate could prompt the user with "We detected a problem: {description}. If you continue, manual fix up may be required. Would you like to ignore this and continue migrating? [y/N]". Basically, I want dotnet-migrate to do the bulk of the conversion work. I don't mind making some manual edits if dotnet-migrate can't do everything automagically...

...of course, take the suggestion with a grain of salt since I'm probably more comfortable hand-editing csproj than most users.

**Comment by piotrpMSFT** [comment]
It leads to an interesting idea:

`dotnet migrate` cannot find a `project.json` file in `directory`. If you've previously migrated that project, please restore the project.json file from the backup folder.

**Comment by Bartmax** [comment]
Why not look in root and backup folder?

Sent from my iPhone 




On Thu, Nov 17, 2016 at 8:52 PM -0300, "Piotr Puszkiewicz" <notifications@github.com> wrote:












It leads to an interesting idea:



dotnet migrate cannot find a project.json file in directory. If you've previously migrated that project, please restore the project.json file from the backup folder.

**Comment by piotrpMSFT** [comment]
Great question. Once #4757 is fixed we'll be able to pursue that. That fix will need to make assumptions about its ability to write to the most common root directory, however, so some sort of escape hatch will be needed [like this error message suggestion].

**Comment by ArieJones** [comment]
@piotrpMSFT I have commented in another issue about this but I believe the problem is probably with the   -s|--skip-project-references  Skip migrating project references. By default project references are migrated recursively

Visual Studio 2017 RC uses this option but it is not being honored.

**Comment by ArieJones** [comment]
Also when I get done with the dance to get all of my projects in my solution migrated .. it says that my web project is migrated but it won't open in Visual Studio 2017 RC 

D:\Development\Workspaces\VS2017\src\Carepilot\Carepilot.csproj : error  : The operation could not be completed. Unspecified error

This is even though it says it has migrated the project properly.... .

`C:\WINDOWS\system32>dotnet migrate -s "D:\Development\Workspaces\VS2017\src\Carepilot" -x "D:\Development\Workspaces\VS2017\src\Carepilot\Carepilot.xproj"
Project Carepilot migration succeeded (D:\Development\Workspaces\VS2017\src\Carepilot)
Summary
Total Projects: 1
Succeeded Projects: 1
Failed Projects: 0`

**Comment by piotrpMSFT** [comment]
I just commented on the other issue @ArieJones and I'll add here as well that I'd love to see the migrated project that's failing. Does it build from the command line?

In case it helps, the issue in VS is not that `--skip-project-references` is ignored. It is actually honored. The issue is that VS is not passing `--skip-backup` which causes a project's project.json to be removed even if overall migration `isn't done with it yet`. This will be fixed soon.

**Comment by ArieJones** [comment]
@piotrpMSFT  What is the purpose of --skip-project-references then?  

Maybe I wasn't clear in my previous post but I ran these commands from the command line and each time it would look for any references project's project.json file even though the option was specified. 

When I specify  a build using the VS 2017 RC command line via 
`devenv /build Debug "D:\Development\Workspaces\VS2017\src\Carepilot\Carepilot.csproj"`

it will build at the solution level and thus skips the project altogether. 

I can provide the .csproj file but not the project itself. I have a few other projects that I will give a go at today to see if they come up with the same issue or not. 

[Carepilot.zip](https://github.com/dotnet/cli/files/608662/Carepilot.zip)

**Comment by ArieJones** [comment]
@piotrpMSFT  I do have another project that I could zip and share with you. On this project it's just jacked.. all projects say they migrated correctly but cannot load any from the solution file. 

I just need an email addy to send the zip file to.

**Comment by ArieJones** [comment]
It also appears that the migration does not handle the following ...leaving junk around .. 

[projectname].xproj.user 
project.lock.json

**Comment by ArieJones** [comment]
When migrating, I also run into a problem where if the migration fails then the project is left in a state where there is a runtimeconfig.template.json file and the migrate command complains that it is already there.... shouldn't it just overwrite the thing.

**Comment by ArieJones** [comment]
So with a project with only single dependency between the projects...
Web -> Common 
Security -> Common 

because I haven't gotten around to adding in the Security class into the web project yet.. .

The migration shows as all successful ....EXCEPT the web project won't open on this one as well. The class libraries are fine.

**Comment by ArieJones** [comment]
The previous project had a more complex chain of dependencies involved.

**Comment by GZidar** [comment]
When attempting to open the project in VS 2017 RC the project doesn't properly load and there are warnings in the errors window with the following message: 

The file '**\*.cs' could not be added to the project.  The specified path contains invalid characters, is an absolute path, or is a path outside of the project directory.

**Comment by piotrpMSFT** [comment]
@ArieJones you've been busy 👍 I hope I don't miss any:
1. `--skip-project-references`
From help text:
> "-s|--skip-project-references", "Skip migrating project references. By default project references are migrated recursively."

This command simply prevents recursive migration of dependencies. It still requires dependency project.json's to be available for the migration of the current project.

2. `devenv /build Debug "D:\Development\Workspaces\VS2017\src\Carepilot\Carepilot.csproj"`
@srivatsn may be able to help with this one. I'm afraid I'm not familiar with `devenv /build`...

3. broken solution
This is a tracked issue: #4632 

4. xproj.user: this was fixed by #4741 

5. project.lock.json: this was fixed by #4829 

6. `runtimeconfig.template.json`
Do you have a repro of this? Can you open another issue to track that one inc. repro?

**Comment by piotrpMSFT** [comment]
@GZidar seems like a related but different issue. Can you open and add a repro?

**Comment by GZidar** [comment]
@piotrpMSFT will see if I can get a simple repro defined.

**Comment by livarcocc** [comment]
If this was tracking the --skip-project-references still looking for a dependency project.json, this was fixed here: https://github.com/dotnet/cli/pull/5352. I am closing this issue.

If there was something else that was being tracked here, I ask that a separate issue get filed for it.
