### ISSUE TITLE
Meta: Blocking RTM issues

### ISSUE THREAD

**Issue by onovotny** [dotnet/cli#5365]
As of today, the Rx.NET solution using xproj/project.json (Rx v3.1.1 in master) does not successfully migrate to the latest CLI tools.

There are several underlying issues that are mostly attributed to unrecognized TFM's.
- [ ] https://github.com/dotnet/sdk/issues/663
- [ ] https://github.com/dotnet/sdk/issues/492
- [ ] https://github.com/dotnet/sdk/issues/491
- [ ] https://github.com/dotnet/cli/issues/4847
- [x] https://github.com/NuGet/Home/issues/4136
- [x] https://github.com/NuGet/Home/issues/4137

There's also an issue of files outside of a project scope not showing up in VS. There's a workaround that I think is good in an RC but is not good enough for an RTM.
- [ ] https://github.com/dotnet/roslyn-project-system/issues/1233

There's one about p2p refs: 
- [ ] https://github.com/dotnet/roslyn-project-system/issues/936

There's an issue with glob's from a parent dir not working correctly
- [ ] https://github.com/Microsoft/msbuild/issues/1576

**Comment by piotrpMSFT** [comment]
@srivatsn @rrelyea

**Comment by rohit21agrawal** [comment]
i believe NuGet/Home#4137 has been fixed

**Comment by piotrpMSFT** [comment]
Closing. We're tracking this meta-issue through the individual issues.
