### ISSUE TITLE
Small footprint self-contained app issues

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#5769]
I have some open issues on problems with the 👣 small footprint 👣 self-contained app:

- [ ] [System.InvalidCastException for small-footprint self-contained test app (aspnet/Configuration #589)](https://github.com/aspnet/Configuration/issues/589)
- [ ] [web.config is incorrect for small footprint self-contained app (aspnet/websdk #108)](https://github.com/aspnet/websdk/issues/108)
- [ ] [Precompiled views are not generated for small footprint self-contained app (aspnet/MvcPrecompilation #73)](https://github.com/aspnet/MvcPrecompilation/issues/73)

@blackdwarf I presume this app type is on the back burner while you work on more important bits but that you want me to leave those three issues open until you get to them.

Do you want to leave this issue open as a tracking issue?

**Comment by blackdwarf** [comment]
@GuardRex we should lave it, yes. Milestoning it as 2.0.0 for tracking.

Just to be clear, can you elaborate on what you mean specifically by "small footprint"?

**Comment by GuardRex** [comment]
[Deploying a self-contained deployment with a smaller footprint](https://docs.microsoft.com/en-us/dotnet/articles/core/deploying/#deploying-a-self-contained-deployment-with-a-smaller-footprint)
