### ISSUE TITLE
DotNetCliToolReference can't target netcoreapp2.0 and have references to 1.x packages

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#6087]
## Steps to reproduce
Create a tool that targets `netcoreapp2.0` and has a dependency that eventually resolves to a `System.*` package from `netstandard1.x` TFM.  For example, retarget https://github.com/dotnet/cli/blob/master/TestAssets/TestPackages/dotnet-dependency-context-test/dotnet-dependency-context-test.csproj in our own test assets to `netcoreapp2.0`.

Reference the tool from a project and invoke it.

## Expected  behavior
The tool executes fine.

## Actual behavior
You get errors like the following:

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Linq, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Argument(String name, String description, Action`1 configuration, Boolean multipleValues)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Argument(String name, String description, Boolean multipleValues)
   at Microsoft.DotNet.Tools.DependencyInvoker.DotnetBaseParams.AddDotnetBaseParameters()
   at Microsoft.DotNet.Tools.DependencyInvoker.DotnetBaseParams..ctor(String name, String fullName, String description)
   at Microsoft.DotNet.Tools.DependencyInvoker.Program.Main(String[] args)
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0-preview1-005473)

Product Information:
 Version:            2.0.0-preview1-005473
 Commit SHA-1 hash:  38f139fd8e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   F:\cli\artifacts\win10-x64\stage2\sdk\2.0.0-preview1-005473\
```

## Notes
This is because `Microsoft.NETCore.App` v2.0 now has all the `System.*` assemblies inside a single nuget package instead of spread out like they were in 1.x.  When we [generate the tool's deps.json](https://github.com/dotnet/cli/blob/70c65160f6163666dbe5f052b2331ec59582fce5/src/Microsoft.DotNet.Cli.Utils/CommandResolution/ProjectToolsCommandResolver.cs#L326) file, we are not doing the conflict resolution that the happens when generating a normal project's deps.json.  Normally, there is a .targets file in NETStandard.Library that does the conflict resolution.  See https://github.com/dotnet/standard/blob/7c681d51a8c1a74a8467f32233e39e65b30bd3f4/Microsoft.Packaging.Tools/tasks/targets/Microsoft.Packaging.Tools.targets#L86-L94.

@livarcocc @dsplaisted @ericstj 

## Tasks

- [ ] Set TFM to use for tool restore in SDK (instead of using hardcoded NuGet version)
  - This will cause tools to roll forward to the CLI's bundled framework
- [ ] Escape hatch to allow restoring for an older TFM (ie to restore and run tool on 1.x)
  - Probably expressed as metadata on the `DotNetCliToolReference`
  - Probably needs to be designed with NuGet team
- [ ] Generate deps.json as part of restore instead of when tool is invoked
  - This will avoid duplication of logic to generate deps.json in CLI and SDK
  - This should also bring in the conflict resolution logic which will fix this bug

**Comment by dsplaisted** [comment]
I'm working on using the .NET SDK targets to generate the deps.json file for an assets.json file of a CLI tool.  I've been able to do so using a project file like the following:

```xml
<Project Sdk="Microsoft.NET.Sdk" DefaultTargets="BuildDepsJson">
  
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <AssemblyName>foo</AssemblyName>
    <OutputType>Exe</OutputType>
    <ProjectAssetsFile>C:\git\dotnet-sdk\packages\.tools\dotnet-clitool\1.0.0-rc\netcoreapp2.0\project.assets.json</ProjectAssetsFile>
    <ProjectDepsFilePath>dotnet-CliTool.deps.json</ProjectDepsFilePath>
  </PropertyGroup>

  <ItemGroup>
    <PackageConflictPlatformManifests Include="C:\Users\daplaist\.dotnet\NuGetFallbackFolder\microsoft.netcore.app\2.0.0-preview1-001913-00\build\netcoreapp2.0\Microsoft.NETCore.App.PlatformManifest.txt" />
  </ItemGroup>

  <Target Name="BuildDepsJson" DependsOnTargets="$(ResolvePackageDependenciesForBuildDependsOn);GenerateBuildDependencyFile" />

</Project>
```

The two issues with this are:

- The deps.json contains entries for the "foo" project itself, which I have to manually delete
- I've had to manually include the PlatformManifest from the Microsoft.NETCore.App package in the `PackageConflictPlatformManifests` item

The entries from the main project in the deps file look like they are comping from the [main project info](https://github.com/dotnet/sdk/blob/39102ec214514363c6af4cd9d599a35aceb8c745/src/Tasks/Microsoft.NET.Build.Tasks/GenerateDepsFile.cs#L119-L124) which is passed [to the DependencyContext](https://github.com/dotnet/sdk/blob/39102ec214514363c6af4cd9d599a35aceb8c745/src/Tasks/Microsoft.NET.Build.Tasks/GenerateDepsFile.cs#L144).  So I think the thing to do would be to make the "Main Project" optional in the DependencyContext, and have an option in the GenerateDepsFile task that would make it not include the main project.  @eerhardt does this make sense?

The `PackageConflictPlatformManifests` item is normally included in a .props file inside the Microsoft.NETCore.App package.  Normally NuGet restore would put an import for that props file in the projectname.g.props file it generates.  @emgarten, would it be possible for NuGet to generate the .props and .targets files when restoring CLI tools and to put them next to the project.assets.json that it puts in the .tools folder?  Or would there be a better way of picking this up?  cc @ericstj for feedback too.

**Comment by emgarten** [comment]
> would it be possible for NuGet to generate the .props and .targets files when restoring CLI tools and to put them next to the project.assets.json that it puts in the .tools folder?

Restore could do this.

**Comment by eerhardt** [comment]
> So I think the thing to do would be to make the "Main Project" optional in the DependencyContext, and have an option in the GenerateDepsFile task that would make it not include the main project. @eerhardt does this make sense?

I think this makes sense.  It can be used in a few other places too.  For example when we build the CLI, we manually go and hack out the "main project info" as well.  See https://github.com/dotnet/cli/blob/67563a4f121f6cc22f76922c904740c47ddf40b7/src/redist/redist.csproj#L62-L64

/cc @livarcocc

**Comment by dsplaisted** [comment]
>> would it be possible for NuGet to generate the .props and .targets files when restoring CLI tools and to put them next to the project.assets.json that it puts in the .tools folder?

> Restore could do this.

I've filed https://github.com/NuGet/Home/issues/5037 for the DotNetCliToolReference restore to generate the .props and targets file in the tool folder.

**Comment by natemcmaster** [comment]
FYI @prafullbhosale @bricelam
