### ISSUE TITLE
Localization work for the CLI

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#6114]
- [x] Produce CLI's satellite assemblies (PR #6800)
- [x] Carry CLI dependencies' satellite assemblies (#5007)
- [x] Pay-for-play (#6877)

Blocking partner issues:
- [x] https://github.com/Microsoft/msbuild/issues/2187 (In PR)
- [x] https://github.com/Microsoft/msbuild/issues/2203 (In PR)
- [ ] https://github.com/NuGet/Home/issues/5382

**Comment by rainersigwald** [comment]
Can you track https://github.com/Microsoft/msbuild/issues/2187 instead of  Microsoft/msbuild#2201 please? I closed the latter as a duplicate of the former.

**Comment by rainersigwald** [comment]
MSBuild PRs out for

- [ ] Microsoft/msbuild#2187
- [ ] https://github.com/Microsoft/msbuild/issues/2203

**Comment by nguerrera** [comment]
> Can you track Microsoft/msbuild#2187 instead of Microsoft/msbuild#2201 please?
Fixed.

**Comment by shaggygi** [comment]
Any reason this is still open?  Only issue left to close milestone?

**Comment by livarcocc** [comment]
We still don't have NuGet satellites.

**Comment by nguerrera** [comment]
Let's use #8471 to track nuget satellites.
