### ISSUE TITLE
dnu parity

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#64]
In the next 2 weeks, we'd like to be able to change the ASP.NET build infrastructure to use dotnet cli. To do that we need to make sure we have parity for most of the commands. This is an issue to track the bare minimum required for us to switch over:

- [x] - Running prebuild, postbuild events in project.json
- [x] - Running prepublish, postpublish events in project.json
- [ ] - Compile module support in the compiler (TBD)
- [x] - Support for resources https://github.com/dotnet/cli/issues/68
  - [x] - Embedded resources
  - [x] - Resx files
- [x] - Support for all compilation options defined in `project.json`
 - [x] - Support for oss signing (see https://github.com/aspnet/Announcements/issues/86) depends on https://github.com/dotnet/roslyn/issues/1171
 - [x] - Support for producing pdbs
 - [x] - Support for producing portable pdbs
 - [x] - Support for language version
- [x] - Support for all 3 OSes (linux, osx, windows)
- [x] - .NET Framework support (as a compilation output)
  - [x] - Support for compiling with mono reference assemblies - This may or may not be a big issue. (this is enabled right now via an env variable). There's still work needed here. See https://github.com/dotnet/corefx/issues/3934
- [x] - Publish to support copying content files to the output folder (aka msbuild's copy to output) - see https://github.com/dotnet/cli/pull/61
- [x] - Showing dependency diagnostics on the command line
- [x] - Disable binding redirect warnings https://github.com/dotnet/cli/issues/47
- [x] - Add support for generating binding redirects for .NET Framework https://github.com/dotnet/cli/issues/397
- [ ] - Globbing support for `dotnet compile`
- [x] - Support generating dll metadata based on `project.json` metadata - https://github.com/dotnet/cli/issues/398
- [x] - Satellite resource assembly generation (today we use roslyn but maybe we need a resgen port?) https://github.com/dotnet/cli/issues/403

## Commands

- [x] - `dotnet run` see https://github.com/dotnet/cli/issues/59
- [x] - `dotnet pack` (dotnet compile -> nuget pack)
 - [x] Generate symbol packages https://github.com/dotnet/cli/issues/495
- [x] - `dotnet test` This one is a little fuzzy. The DNX handles testing very differently but we can do something here.

## Engineering
- [ ] - Performance needs to be as good as `dnu build` - Was using in roslyn in memory, so saw all the benefits of caching metadata refs and syntax trees (for cross compile)

**Comment by piotrpMSFT** [comment]
@davidfowl, can you update this list and make sure we have issues tracking remaining work?

**Comment by andschwa** [comment]
@davidfowl is there any preview I can use for `dotnet-test`? We've had to switch from DNX to `dotnet-cli`, but it means we can no longer run our xUnit tests.
