### ISSUE TITLE
[tools] December summary issue

### ISSUE THREAD

**Issue by wli3** [dotnet/cli#8067]
- [x] Obtain Package, Construct fake project and restore to custom folder https://github.com/dotnet/cli/issues/8062
- [x] Generate Shim, Find XML of metadata update shim  https://github.com/dotnet/cli/issues/8063
- [x] Generate Shim, Proper execute permission for both shim and executable from package https://github.com/dotnet/cli/issues/8064
- [x] Add Shim to Path https://github.com/dotnet/cli/issues/8065
- [x] Write install command parser https://github.com/dotnet/cli/issues/8066 PR:#8132
- [x] loc https://github.com/dotnet/cli/issues/8078

Nuget Ask: NuGet/Home#6200

**Comment by wli3** [comment]
@livarcocc FYI

**Comment by wli3** [comment]
Nuget Ask: https://github.com/NuGet/Home/issues/6200

**Comment by enricosada** [comment]
@wli3 there is any doc/issue about this feature?

i think is the global commands , and i really like to use that for `paket`/`fake` and others too.

Is related to https://github.com/dotnet/cli/issues/4723 ? so command will be per repo? or just per sdk?

/cc @livarcocc

**Comment by wli3** [comment]
@KathleenDollard

**Comment by wli3** [comment]
#8133

**Comment by wli3** [comment]
- [ ] https://github.com/dotnet/cli/issues/8162

**Comment by wli3** [comment]
@enricosada Let me answer what I can. I will need help from @KathleenDollard for the rest.

For what is in the master. It is not machine wide. It is user wide. It doesn't care about sdk version, but it does care about **runtime version**. It follows the current runtime policy. If the tool requires runtime version that is not compatible/available on the consumer's machine. The consumer will need to install the runtime the tool asked.

**Comment by KathleenDollard** [comment]
@enricosada 

Apologies for the slow response, I've been out a bit. 

This is the first step and looking forward to seeing how it fits your needs as we have a few ideas for next steps. 

Are your bullets things you think we will need, or a question about what we have in this release?
