### ISSUE TITLE
local tool summary issue

### ISSUE THREAD

**Issue by wli3** [dotnet/cli#9924]
- [x] https://github.com/dotnet/cli/issues/9917 dotnet tool install/uninstall
- [x] https://github.com/dotnet/cli/issues/9918 Manifest serialization/deserialization 
- [x] https://github.com/dotnet/cli/issues/9919 dotnet tool restore
- [x] https://github.com/dotnet/cli/issues/9920 dotnet tool list <--local>
- [x] https://github.com/dotnet/cli/issues/9921 Store to nuget global package folder and find the dll
- [x] https://github.com/dotnet/cli/issues/9922 Local tool Command Resolver
- [x] https://github.com/dotnet/cli/issues/9923 dll missing handing
- [x] https://github.com/dotnet/cli/issues/10040 security review
- [x] https://github.com/dotnet/cli/issues/10259 new manifest file

**Comment by livarcocc** [comment]
Closing the epic is the known work is done. Onward to bugs.
